<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="roomba">

  <!-- Robot Parameters -->
  <xacro:property name="base_length" value="0.193"/>
  <xacro:property name="base_width" value="0.110"/>
  <xacro:property name="base_height" value="0.006"/>
  
  <!-- Top chassis parameters (adjust these based on your actual robot) -->
  <xacro:property name="top_length" value="0.193"/>
  <xacro:property name="top_width" value="0.110"/>
  <xacro:property name="top_height" value="0.006"/>
  <xacro:property name="chassis_separation" value="0.04"/>  <!-- Distance between bottom and top chassis -->
  
  <xacro:property name="wheel_radius" value="0.03"/>
  <xacro:property name="wheel_thickness" value="0.02"/>
  
  <!-- Material Definitions -->
  <material name="blue">
    <color rgba="0.0 0.0 1.0 1.0"/>
  </material>
  
  <material name="gray">
    <color rgba="0.5 0.5 0.5 1.0"/>
  </material>
  
  <material name="red">
    <color rgba="1.0 0.0 0.0 1.0"/>
  </material>
  
  <material name="green">
    <color rgba="0.0 1.0 0.0 1.0"/>
  </material>
  
  <material name="black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>
  
  <material name="white">
    <color rgba="1.0 1.0 1.0 1.0"/>
  </material>

  <!-- Base Link (Bottom Chassis - for wheels) -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <mass value="1.0"/>
      <inertia ixx="0.003" ixy="0.0" ixz="0.0"
               iyy="0.003" iyz="0.0"
               izz="0.005"/>
    </inertial>
  </link>

  <!-- Top Chassis Link (for sensors) -->
  <link name="top_chassis">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${top_length} ${top_width} ${top_height}"/>
      </geometry>
      <material name="gray"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${top_length} ${top_width} ${top_height}"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.5"/>
      <inertia ixx="0.002" ixy="0.0" ixz="0.0"
               iyy="0.002" iyz="0.0"
               izz="0.003"/>
    </inertial>
  </link>

  <joint name="top_chassis_joint" type="fixed">
    <parent link="base_link"/>
    <child link="top_chassis"/>
    <origin xyz="0 0 ${chassis_separation}" rpy="0 0 0"/>
  </joint>

  <!-- Wheel Macro -->
  <xacro:macro name="wheel" params="name x y z">
    <link name="${name}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
        <material name="black"/>
      </visual>
      
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
      </collision>
      
      <inertial>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <mass value="0.1"/>
        <inertia ixx="0.0005" ixy="0.0" ixz="0.0"
                 iyy="0.0005" iyz="0.0"
                 izz="0.0009"/>
      </inertial>
    </link>

    <joint name="${name}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}_wheel"/>
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- Create All Four Wheels (attached to base_link) -->
  <xacro:wheel name="front_left" x="0.0625" y="0.074" z="0.011"/>
  <xacro:wheel name="front_right" x="0.0625" y="-0.074" z="0.011"/>
  <xacro:wheel name="rear_left" x="-0.0625" y="0.074" z="0.011"/>
  <xacro:wheel name="rear_right" x="-0.0625" y="-0.074" z="0.011"/>

  <!-- IMU Link (mounted on top chassis) -->
  <link name="imu_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.02 0.02 0.01"/>
      </geometry>
      <material name="red"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.02 0.02 0.01"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.01"/>
      <inertia ixx="0.00001" ixy="0.0" ixz="0.0"
               iyy="0.00001" iyz="0.0"
               izz="0.00001"/>
    </inertial>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="top_chassis"/>
    <child link="imu_link"/>
    <!-- Adjust these coordinates relative to top_chassis -->
    <origin xyz="0.05 0.01 ${top_height/2 + 0.005}" rpy="0 0 0"/>
  </joint>

  <!-- Ultrasonic Sensor Link (mounted on top chassis) -->
  <link name="ultrasonic_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.008" length="0.02"/>
      </geometry>
      <material name="green"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.008" length="0.02"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.01"/>
      <inertia ixx="0.00001" ixy="0.0" ixz="0.0"
               iyy="0.00001" iyz="0.0"
               izz="0.00001"/>
    </inertial>
  </link>

  <joint name="ultrasonic_joint" type="fixed">
    <parent link="top_chassis"/>
    <child link="ultrasonic_link"/>
    <!-- Adjust these coordinates relative to top_chassis -->
    <origin xyz="0.06 0.03 ${top_height/2 + 0.01}" rpy="0 0 0"/>
  </joint>

  <!-- Camera Link (mounted on top chassis) -->
  <link name="camera_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.02 0.02 0.01"/>
      </geometry>
      <material name="white"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.02 0.02 0.01"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.01"/>
      <inertia ixx="0.00001" ixy="0.0" ixz="0.0"
               iyy="0.00001" iyz="0.0"
               izz="0.00001"/>
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <parent link="top_chassis"/>
    <child link="camera_link"/>
    <!-- Adjust these coordinates relative to top_chassis -->
    <origin xyz="0.05 -0.01 ${top_height/2 + 0.005}" rpy="0 0 0"/>
  </joint>

</robot>
